# Generated by Django 4.0.4 on 2022-10-12 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cm_name', models.CharField(max_length=50)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'ケアマネジャー',
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10, verbose_name='性別')),
            ],
            options={
                'verbose_name_plural': '性別',
            },
        ),
        migrations.CreateModel(
            name='Kaigodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kaigodo', models.CharField(max_length=4)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '介護度',
            },
        ),
        migrations.CreateModel(
            name='Medical_Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_insurance', models.CharField(max_length=255, verbose_name='医療保険種別')),
            ],
            options={
                'verbose_name_plural': '医療保険',
            },
        ),
        migrations.CreateModel(
            name='Ninchisho_Jiritudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ninchisho_koureisha', models.CharField(max_length=10, verbose_name='認知症自立度')),
            ],
            options={
                'verbose_name_plural': '認知症自立度',
            },
        ),
        migrations.CreateModel(
            name='Pension_Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_insurance', models.CharField(max_length=255, verbose_name='年金種別')),
            ],
            options={
                'verbose_name_plural': '年金',
            },
        ),
        migrations.CreateModel(
            name='Riyousha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hihoken_no', models.CharField(max_length=10, null=True, verbose_name='被保険者番号')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='氏名')),
                ('name_kana', models.CharField(max_length=100, null=True, verbose_name='氏名カナ')),
                ('nyuuryoku_date', models.DateField(null=True, verbose_name='入力日')),
                ('birth_day', models.DateField(null=True, verbose_name='生年月日')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('gender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hana_cm.Riyousha.gender+', to='hana_cm.gender', verbose_name='性別')),
            ],
            options={
                'verbose_name_plural': '利用者',
            },
        ),
        migrations.CreateModel(
            name='Shogai_Jiritudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shougai_koureisha', models.CharField(max_length=10, verbose_name='障害自立度')),
            ],
            options={
                'verbose_name_plural': '障害自立度',
            },
        ),
        migrations.CreateModel(
            name='RiyoushaAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nyuuryoku_date', models.DateTimeField(null=True, verbose_name='フェイスシート入力日')),
                ('post_no', models.CharField(max_length=8, null=True, verbose_name='郵便番号')),
                ('adress', models.CharField(max_length=100, null=True, verbose_name='住所')),
                ('youkaigodo_nyuuryokuDate', models.DateField(null=True, verbose_name='認定情報入力日')),
                ('nintei_date', models.DateField(null=True, verbose_name='認定日')),
                ('start_date', models.DateField(null=True, verbose_name='認定開始日')),
                ('end_date', models.DateField(null=True, verbose_name='認定終了日')),
                ('shuso_honninn', models.TextField(null=True, verbose_name='主訴（本人）')),
                ('shuso_family', models.TextField(null=True, verbose_name='主訴（家族）')),
                ('family_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='家族氏名')),
                ('family_relationship', models.CharField(blank=True, max_length=10, null=True, verbose_name='続柄')),
                ('family_phone', models.CharField(blank=True, max_length=14, null=True, verbose_name='電話番号')),
                ('life_history', models.TextField(null=True, verbose_name='生活歴')),
                ('disease_history', models.TextField(null=True, verbose_name='病歴')),
                ('cm_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hana_cm.Riyousha.cm_name +', to='hana_cm.caremanager', verbose_name='担当ケアマネ')),
                ('kaigodo', models.ForeignKey(db_column='kaigodo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Riyousha_kaigodo', to='hana_cm.kaigodo', verbose_name='要介護度')),
                ('medical_insurance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insurance', to='hana_cm.medical_insurance', verbose_name='医療保険')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riyousha_attributes', to='hana_cm.riyousha', verbose_name='氏名')),
                ('ninchisho_koureisha', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hana_cm.RiyoushaAttributes.ninchisho_jkoureisha+', to='hana_cm.ninchisho_jiritudo', verbose_name='認知症高齢者自立度')),
                ('pension_insurance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pension_insurance', to='hana_cm.pension_insurance', verbose_name='年金')),
                ('shougai_koureisha', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hana_cm.RiyoushaAttributes.shougai_koureisha+', to='hana_cm.shogai_jiritudo', verbose_name='障害高齢者自立度')),
            ],
            options={
                'verbose_name_plural': '利用者フェイスシート',
            },
        ),
        migrations.CreateModel(
            name='Adl_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nyuuryoku_date', models.DateField(verbose_name='入力基準日')),
                ('non', models.BooleanField(help_text='「なし」なら、チェックしてください', verbose_name='麻痺なし')),
                ('left_upper_limbs', models.BooleanField(choices=[(False, 'なし'), (True, 'あり')], help_text='「左上肢に麻痺」があれば、チェックしてください', null=True, verbose_name='左上肢')),
                ('left_lower_limbs', models.BooleanField(choices=[(False, 'なし'), (True, 'あり')], help_text='「左下肢に麻痺」があれば、チェックしてください', null=True, verbose_name='左下肢')),
                ('right_upper_limbs', models.BooleanField(choices=[(False, 'なし'), (True, 'あり')], help_text='「右上肢に麻痺」があれば、チェックしてください', null=True, verbose_name='右上肢')),
                ('right_lower_limbs', models.BooleanField(choices=[(False, 'なし'), (True, 'あり')], help_text='「右下肢に麻痺」があれば、チェックしてください', null=True, verbose_name='右下肢')),
                ('others', models.BooleanField(help_text='「その他」があれば、チェックしてください。詳細を「麻痺その他」に記入してください', null=True, verbose_name='その他')),
                ('paralysis_others', models.CharField(max_length=50, null=True, verbose_name='その他詳細')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('riyousha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hana_cm.riyousha', verbose_name='利用者')),
            ],
            options={
                'verbose_name_plural': 'アセスメント',
            },
        ),
    ]
