# Generated by Django 4.0.4 on 2022-10-13 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hana_cm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riyoushaattributes',
            name='adress',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='住所'),
        ),
        migrations.AlterField(
            model_name='riyoushaattributes',
            name='cm_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hana_cm.Riyousha.cm_name +', to='hana_cm.caremanager', verbose_name='担当ケアマネ'),
        ),
        migrations.AlterField(
            model_name='riyoushaattributes',
            name='disease_history',
            field=models.TextField(blank=True, null=True, verbose_name='病歴'),
        ),
        migrations.AlterField(
            model_name='riyoushaattributes',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='認定終了日'),
        ),
        migrations.AlterField(
            model_name='riyoushaattributes',
            name='kaigodo',
            field=models.ForeignKey(blank=True, db_column='kaigodo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Riyousha_kaigodo', to='hana_cm.kaigodo', verbose_name='要介護度'),
        ),
        migrations.AlterField(
            model_name='riyoushaattributes',
            name='life_history',
            field=models.TextField(blank=True, null=True, verbose_name='生活歴'),
        ),
        migrations.AlterField(
            model_name='riyoushaattributes',
            name='medical_insurance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insurance', to='hana_cm.medical_insurance', verbose_name='医療保険'),
        ),
        migrations.AlterField(
            model_name='riyoushaattributes',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='riyousha_attributes', to='hana_cm.riyousha', verbose_name='氏名'),
        ),
        migrations.AlterField(
            model_name='riyoushaattributes',
            name='ninchisho_koureisha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hana_cm.RiyoushaAttributes.ninchisho_jkoureisha+', to='hana_cm.ninchisho_jiritudo', verbose_name='認知症高齢者自立度'),
        ),
        migrations.AlterField(
            model_name='riyoushaattributes',
            name='nintei_date',
            field=models.DateField(blank=True, null=True, verbose_name='認定日'),
        ),
        migrations.AlterField(
            model_name='riyoushaattributes',
            name='nyuuryoku_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='フェイスシート入力日'),
        ),
        migrations.AlterField(
            model_name='riyoushaattributes',
            name='pension_insurance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pension_insurance', to='hana_cm.pension_insurance', verbose_name='年金'),
        ),
        migrations.AlterField(
            model_name='riyoushaattributes',
            name='post_no',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='郵便番号'),
        ),
        migrations.AlterField(
            model_name='riyoushaattributes',
            name='shougai_koureisha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hana_cm.RiyoushaAttributes.shougai_koureisha+', to='hana_cm.shogai_jiritudo', verbose_name='障害高齢者自立度'),
        ),
        migrations.AlterField(
            model_name='riyoushaattributes',
            name='shuso_family',
            field=models.TextField(blank=True, null=True, verbose_name='主訴（家族）'),
        ),
        migrations.AlterField(
            model_name='riyoushaattributes',
            name='shuso_honninn',
            field=models.TextField(blank=True, null=True, verbose_name='主訴（本人）'),
        ),
        migrations.AlterField(
            model_name='riyoushaattributes',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='認定開始日'),
        ),
        migrations.AlterField(
            model_name='riyoushaattributes',
            name='youkaigodo_nyuuryokuDate',
            field=models.DateField(blank=True, null=True, verbose_name='認定情報入力日'),
        ),
    ]
