# Generated by Django 4.0.4 on 2022-10-13 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hana_cm', '0002_alter_riyoushaattributes_adress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riyoushaattributes',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='riyousha_attributes', to='hana_cm.riyousha', verbose_name='氏名'),
        ),
    ]
