# Generated by Django 4.0.4 on 2022-10-14 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hana_cm', '0003_alter_riyoushaattributes_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='riyoushaattributes',
            name='family_name2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='家族氏名'),
        ),
        migrations.AddField(
            model_name='riyoushaattributes',
            name='family_name3',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='家族氏名'),
        ),
        migrations.AddField(
            model_name='riyoushaattributes',
            name='family_phone2',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='電話番号'),
        ),
        migrations.AddField(
            model_name='riyoushaattributes',
            name='family_phone3',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='電話番号'),
        ),
        migrations.AddField(
            model_name='riyoushaattributes',
            name='family_relationship2',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='続柄'),
        ),
        migrations.AddField(
            model_name='riyoushaattributes',
            name='family_relationship3',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='続柄'),
        ),
    ]
