# Generated by Django 4.0.4 on 2022-10-14 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hana_cm', '0004_riyoushaattributes_family_name2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riyoushaattributes',
            name='family_situation',
            field=models.TextField(blank=True, null=True, verbose_name='家族の状況'),
        ),
    ]
