# Generated by Django 4.0.4 on 2022-10-14 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hana_cm', '0005_riyoushaattributes_family_situation'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrequencyOfHospitalVisits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency_of_hospital_visits', models.CharField(blank=True, max_length=10, null=True, verbose_name='通院頻度')),
            ],
            options={
                'verbose_name_plural': '通院頻度',
            },
        ),
        migrations.AddField(
            model_name='riyoushaattributes',
            name='desease_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='家族氏名'),
        ),
        migrations.AddField(
            model_name='riyoushaattributes',
            name='frequency',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='電話番号'),
        ),
        migrations.AddField(
            model_name='riyoushaattributes',
            name='primary_care_doctor',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='続柄'),
        ),
    ]
