# Generated by Django 4.0.4 on 2022-10-14 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hana_cm', '0006_frequencyofhospitalvisits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riyoushaattributes',
            name='desease_name2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='病名2'),
        ),
        migrations.AddField(
            model_name='riyoushaattributes',
            name='desease_name3',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='病名2'),
        ),
        migrations.AddField(
            model_name='riyoushaattributes',
            name='frequency2',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='通院頻度2'),
        ),
        migrations.AddField(
            model_name='riyoushaattributes',
            name='frequency3',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='通院頻度2'),
        ),
        migrations.AddField(
            model_name='riyoushaattributes',
            name='primary_care_doctor2',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='主治医2'),
        ),
        migrations.AddField(
            model_name='riyoushaattributes',
            name='primary_care_doctor3',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='主治医2'),
        ),
        migrations.AlterField(
            model_name='riyoushaattributes',
            name='desease_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='病名'),
        ),
        migrations.AlterField(
            model_name='riyoushaattributes',
            name='frequency',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='通院頻度'),
        ),
        migrations.AlterField(
            model_name='riyoushaattributes',
            name='primary_care_doctor',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='主治医'),
        ),
    ]
