# Generated by Django 4.0.4 on 2022-10-14 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hana_cm', '0007_riyoushaattributes_desease_name2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequencyofhospitalvisits',
            name='frequency_of_hospital_visits',
            field=models.CharField(max_length=10, verbose_name='通院頻度'),
        ),
    ]
