# Generated by Django 4.0.4 on 2022-10-14 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hana_cm', '0008_alter_frequencyofhospitalvisits_frequency_of_hospital_visits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequencyofhospitalvisits',
            name='frequency_of_hospital_visits',
            field=models.CharField(max_length=10, null=True, verbose_name='通院頻度'),
        ),
    ]
