# Generated by Django 4.0.4 on 2022-10-14 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hana_cm', '0009_alter_frequencyofhospitalvisits_frequency_of_hospital_visits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riyoushaattributes',
            name='frequency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hana_cm.FrequencyOfHospitalVisits+', to='hana_cm.frequencyofhospitalvisits', verbose_name='通院頻度'),
        ),
        migrations.AlterField(
            model_name='riyoushaattributes',
            name='frequency2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hana_cm.FrequencyOfHospitalVisits2+', to='hana_cm.frequencyofhospitalvisits', verbose_name='通院頻度2'),
        ),
        migrations.AlterField(
            model_name='riyoushaattributes',
            name='frequency3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hana_cm.FrequencyOfHospitalVisits3+', to='hana_cm.frequencyofhospitalvisits', verbose_name='通院頻度3'),
        ),
    ]
