# Generated by Django 4.0.4 on 2022-10-14 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hana_cm', '0010_alter_riyoushaattributes_frequency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riyoushaattributes',
            name='othe_frequency',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='その他通院頻度'),
        ),
        migrations.AddField(
            model_name='riyoushaattributes',
            name='othe_frequency2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='その他通院頻度2'),
        ),
        migrations.AddField(
            model_name='riyoushaattributes',
            name='othe_frequency3',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='その他通院頻度3'),
        ),
    ]
