# Generated by Django 4.0.4 on 2022-10-14 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hana_cm', '0011_riyoushaattributes_othe_frequency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisabilityNotebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disability_notebook', models.CharField(max_length=10, null=True, verbose_name='障害障害者手帳')),
            ],
            options={
                'verbose_name_plural': '障害者手帳',
            },
        ),
    ]
