# Generated by Django 4.0.4 on 2022-10-14 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hana_cm', '0012_disabilitynotebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='riyoushaattributes',
            name='disability_notebook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insurance', to='hana_cm.disabilitynotebook', verbose_name='障害者手帳'),
        ),
    ]
