# Generated by Django 4.0.4 on 2022-10-14 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hana_cm', '0013_riyoushaattributes_disability_notebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='riyoushaattributes',
            name='current_service',
            field=models.TextField(blank=True, null=True, verbose_name='生活歴'),
        ),
    ]
