# Generated by Django 4.0.4 on 2022-10-15 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hana_cm', '0014_riyoushaattributes_current_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riyoushaattributes',
            name='nyuuryoku_date',
            field=models.DateField(blank=True, null=True, verbose_name='フェイスシート入力日'),
        ),
    ]
