# Generated by Django 4.0.4 on 2022-10-15 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hana_cm', '0015_alter_riyoushaattributes_nyuuryoku_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExaminationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examination_status', models.CharField(max_length=10, null=True, verbose_name='診察状況')),
            ],
            options={
                'verbose_name_plural': '診察状況',
            },
        ),
    ]
