# Generated by Django 4.0.4 on 2022-10-15 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hana_cm', '0017_riyoushaattributes_examination_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riyoushaattributes',
            name='examination_status',
        ),
        migrations.AddField(
            model_name='riyoushaattributes',
            name='examination_status2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hana_cm.ExaminationStatus2+', to='hana_cm.examinationstatus', verbose_name='診察状況2'),
        ),
        migrations.AddField(
            model_name='riyoushaattributes',
            name='examination_status3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hana_cm.ExaminationStatus3+', to='hana_cm.examinationstatus', verbose_name='診察状況3'),
        ),
    ]
