# Generated by Django 4.0.4 on 2022-11-15 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hana_cm', '0020_riyoushaattributes_pub_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adl_1',
            name='nyuuryoku_date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hana_cm.riyoushaattributes', verbose_name='入力基準日'),
        ),
    ]
