# Generated by Django 4.0.4 on 2022-11-15 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hana_cm', '0021_alter_adl_1_nyuuryoku_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiyoushaAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('non', models.BooleanField(help_text='「なし」なら、チェックしてください', verbose_name='麻痺なし')),
                ('left_upper_limbs', models.BooleanField(choices=[(False, 'なし'), (True, 'あり')], help_text='「左上肢に麻痺」があれば、チェックしてください', null=True, verbose_name='左上肢')),
                ('left_lower_limbs', models.BooleanField(choices=[(False, 'なし'), (True, 'あり')], help_text='「左下肢に麻痺」があれば、チェックしてください', null=True, verbose_name='左下肢')),
                ('right_upper_limbs', models.BooleanField(choices=[(False, 'なし'), (True, 'あり')], help_text='「右上肢に麻痺」があれば、チェックしてください', null=True, verbose_name='右上肢')),
                ('right_lower_limbs', models.BooleanField(choices=[(False, 'なし'), (True, 'あり')], help_text='「右下肢に麻痺」があれば、チェックしてください', null=True, verbose_name='右下肢')),
                ('others', models.BooleanField(help_text='「その他」があれば、チェックしてください。詳細を「麻痺その他」に記入してください', null=True, verbose_name='その他')),
                ('paralysis_others', models.CharField(max_length=50, null=True, verbose_name='その他詳細')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hana_cm.riyoushaattributes', verbose_name='利用者')),
            ],
            options={
                'verbose_name_plural': 'アセスメント',
            },
        ),
        migrations.DeleteModel(
            name='Adl_1',
        ),
    ]
