# Generated by Django 4.0.4 on 2022-11-15 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hana_cm', '0023_riyoushaassessment_nyuuryoku_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riyoushaassessment',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assess_name', to='hana_cm.riyoushaattributes', verbose_name='利用者'),
        ),
    ]
