# Generated by Django 4.0.4 on 2022-11-22 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hana_cm', '0025_remove_riyoushaattributes_pub_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='riyoushaattributes',
            name='pub_datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
